url: 'https://misc-hosting.github.io/aminolink/'
baseurl: '/aminolink'
title: 'Aminolink Peptides'

plugins:
  - jekyll-postcss-v2

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock

destination: docs/
collections:
  - teamMembers
